### ISSUE TITLE
Add freme ner datasets to the images

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#16]

**Comment by jnehring** [comment]
I suggest that using the Dockerfiles we create the images without data. Then we add all the data (both freme-ner and virtuoso data) to the images and tag the containers freme-mysql, freme-virtuoso and freme-solr. Then we can create a docker-compose file that starts up the images with data.

I think this way is the easiest to implement. It makes it more complicated to update the datasets because there is no script to reproduce how to add all datasets to the image but I think this is ok.

**Comment by sandroacoelho** [comment]
Hi @jnehring , @m1ci 

[Solr](https://github.com/freme-project/freme-docker/blob/master/freme-ner-old/docker-compose.yml#L17) is file-oriented with data/metadata self-contained by cores (Solr dataset) stored under server/solr/ folder. So you can build an index, pack and distribute  it with a simple copy and paste. 

Virtuoso  has a more sophisticated mechanism because it is an RDBMS/Triple store, but checking the documentation it is also possible to use copy and paste. Please check it out in this [technical tutorial](http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtuosoDocker).

So, we just need to know how the people would like to combine the datasets to provide these pre-built files.

**Comment by jnehring** [comment]
Next step: Add the remaining dbpedia datasets and Europeana

**Comment by jnehring** [comment]
this issue is solved
